curso/aperitivos/urls.py
from django.urls import path

from curso.aperitivos.views import video, indice


app_name = 'aperitivos'
urlpatterns = [
    path('<slug:slug>', video, name='video'),
    path('', indice, name='indice'),
]

curso/base/urls.py
from django.urls import path

from curso.base.views import home


app_name = 'base'
urlpatterns = [
    path('', home, name='home'),
]

curso/modulos/urls.py
from django.urls import path

from curso.modulos import views


app_name = 'modulos'
urlpatterns = [
    path('form', views.form, name='form'),
    path('<slug:slug>', views.detalhe, name='detalhe'),
    path('aulas/<slug:slug>', views.aula, name='aula'),
    path('api/aulas/<slug:slug>', views.aula_api, name='aula_api'),
    path('', views.indice, name='indice'),
]

curso/turmas/urls.py
from django.urls import path

from curso.turmas import views


app_name = 'turmas'
urlpatterns = [
    path('', views.indice, name='indice'),
]

curso/urls.py
from django.conf import settings
from django.contrib import admin
from django.urls import path, include


urlpatterns = [
    path('admin/', admin.site.urls),
    path('contas/', include('django.contrib.auth.urls')),
    path('', include('curso.base.urls')),
    path('aperitivos/', include('curso.aperitivos.urls')),
    path('modulos/', include('curso.modulos.urls')),
    path('turmas/', include('curso.turmas.urls')),
]

if settings.DEBUG:
    import debug_toolbar
    urlpatterns.append(
        path('__debug__/', include(debug_toolbar.urls)),
    )

curso/aperitivos/models.py
from django.db import models
from django.urls import reverse


class Video(models.Model):
    titulo = models.CharField(max_length=32)
    slug = models.SlugField(max_length=32)
    vimeo_id = models.CharField(max_length=32)
    creation = models.DateTimeField(auto_now_add=True)

    def get_absolute_url(self):
        return reverse('aperitivos:video', args=(self.slug,))

    def __str__(self):
        return f'Video: {self.titulo}'

curso/base/models.py
from django.contrib.auth.base_user import AbstractBaseUser, BaseUserManager
from django.contrib.auth.models import PermissionsMixin
from django.db import models
from django.utils.translation import gettext_lazy as _
from django.utils import timezone
from django.core.mail import send_mail


class UserManager(BaseUserManager):
    use_in_migrations = True

    def _create_user(self, email, password, **extra_fields):
        """
        Create and save a user with the given email and password.
        """
        if not email:
            raise ValueError('The given email must be set')
        email = self.normalize_email(email)
        user = self.model(email=email, **extra_fields)
        user.set_password(password)
        user.save(using=self._db)
        return user

    def create_user(self, email, password=None, **extra_fields):
        extra_fields.setdefault('is_superuser', False)
        return self._create_user(email, password, **extra_fields)

    def create_superuser(self, email, password, **extra_fields):
        extra_fields.setdefault('is_staff', True)
        extra_fields.setdefault('is_superuser', True)

        if extra_fields.get('is_staff') is not True:
            raise ValueError('Superuser must have is_staff=True.')
        if extra_fields.get('is_superuser') is not True:
            raise ValueError('Superuser must have is_superuser=True.')

        return self._create_user(email, password, **extra_fields)


class User(AbstractBaseUser, PermissionsMixin):
    """
    App base User class.

    Email and password are required. Other fields are optional.
    """

    first_name = models.CharField(_('first name'), max_length=30, blank=True)
    email = models.EmailField(_('email address'), unique=True)  # usuario único
    # is_staff def usuarios q podem acessar o admin do django
    is_staff = models.BooleanField(
        _('staff status'),
        default=False,
        help_text=_('Designates whether the user can log into this admin site.'),
    )
    # is_active def usuário q pode se logar dentro do sistema
    is_active = models.BooleanField(
        _('active'),
        default=True,
        help_text=_(
            'Designates whether this user should be treated as active. '
            'Unselect this instead of deleting accounts.'
        ),
    )
    # date_joined def data q o usuario entrou no sistema
    date_joined = models.DateTimeField(_('date joined'), default=timezone.now)

    objects = UserManager()

    EMAIL_FIELD = 'email'
    USERNAME_FIELD = 'email'
    REQUIRED_FIELDS = []

    class Meta:
        verbose_name = _('user')
        verbose_name_plural = _('users')

    def clean(self):
        super().clean()
        self.email = self.__class__.objects.normalize_email(self.email)

    def get_full_name(self):
        """
        Return the first_name plus the last_name, with a space in between.
        """
        full_name = '%s' % (self.first_name)
        return full_name.strip()

    def get_short_name(self):
        """Return the short name for the user."""
        return self.first_name

    def email_user(self, subject, message, from_email=None, **kwargs):
        """Send an email to this user."""
        send_mail(subject, message, from_email, [self.email], **kwargs)

curso/modulos/models.py
from django.db import models
from django.urls import reverse
from ordered_model.models import OrderedModel


# Create your models here.
class Modulo(OrderedModel):
    titulo = models.CharField(max_length=64)
    publico = models.TextField()
    descricao = models.TextField()
    slug = models.SlugField(unique=True)

    class Meta(OrderedModel.Meta):
        pass

    def __str__(self):
        return self.titulo

    def get_absolute_url(self):
        return reverse('modulos:detalhe', kwargs={'slug': self.slug})


class Aula(OrderedModel):
    titulo = models.CharField(max_length=64)
    slug = models.SlugField(unique=True)
    modulo = models.ForeignKey(Modulo, on_delete=models.PROTECT)
    order_with_respect_to = 'modulo'
    vimeo_id = models.CharField(max_length=32)

    class Meta(OrderedModel.Meta):
        pass

    def __str__(self):
        return self.titulo

    def get_absolute_url(self):
        return reverse('modulos:aula', kwargs={'slug': self.slug})

curso/turmas/models.py
from django.db import models
from django.contrib.auth import get_user_model


# Create your models here.
class Turma(models.Model):
    nome = models.CharField(max_length=64)
    slug = models.SlugField(max_length=64)
    inicio = models.DateField()
    fim = models.DateField()
    alunos = models.ManyToManyField(get_user_model(), through='Matricula')


class Matricula(models.Model):
    data = models.DateTimeField(auto_now_add=True)
    usuario = models.ForeignKey(get_user_model(), on_delete=models.CASCADE)
    turma = models.ForeignKey(Turma, on_delete=models.CASCADE)

    class Meta:
        unique_together = [['usuario', 'turma']]
        ordering = ['turma', 'data']

curso/aperitivos/views.py
from django.shortcuts import get_object_or_404, render
from curso.aperitivos.models import Video


def indice(request):
    videos = Video.objects.order_by('creation').all()
    return render(request, 'aperitivos/indice.html', context={'videos': videos})


def video(request, slug):
    video = get_object_or_404(Video, slug=slug)
    return render(request, 'aperitivos/video.html', context={'video': video})

curso/base/views.py
from django.shortcuts import render

# Create your views here.


def home(request):
    return render(request, 'base/home.html')

curso/modulos/views.py
from django.shortcuts import render
from django.contrib.auth.decorators import login_required
from curso.modulos import facade
from django.http import JsonResponse


def indice(request):
    ctx = {'modulos': facade.listar_modulos_com_aulas()}
    return render(request, 'modulos/indice.html', ctx)


def detalhe(request, slug):
    modulo = facade.encontrar_modulo(slug)
    aulas = facade.listar_aulas_de_modulo_ordenadas(modulo)
    return render(request, 'modulos/modulo_detalhe.html', {'modulo': modulo, 'aulas': aulas})


@login_required
def aula(request, slug):
    aula = facade.encontrar_aula(slug)
    return render(request, 'modulos/aula_detalhe.html', {'aula': aula})


@login_required
def form(request):
    modulos = facade.listar_modulos_ordenados()
    return render(request, 'modulos/modulo_form.html', {'modulos': modulos})


def aula_api(request, slug):
    return JsonResponse({
        'aulas': [{'slug': aula.slug, 'titulo': aula.titulo} for aula in facade.listar_aulas_de_modulo(slug)]
    })

curso/turmas/views.py
from django.shortcuts import render


def indice(request):
    return render(request, 'turmas/indice.html')

curso/aperitivos/templates/aperitivos/indice.html
{% extends 'base/base.html' %}
{% load static %}
{% block title %}Rios de Luz - Aperitivos{% endblock title %}
{% block description %}página com videos gratuitos{% endblock description %}
{% block body %}
<div class="container">
    <div class="row">
        <div class="col-md-12">
            <h1 class="mt-4 mb-3">Lista de videos</h1>
            <ol>
                {% for video in videos %}
                    <li><a href="{{ video.get_absolute_url }}">{{ video.titulo | default:"Faltando titulo"}}</li></a>
                {% empty %}
                    <li>Não foi encontrado nenhum vídeo de Aperitivos</li>
                {% endfor %}
            </ol>

        </div>
    </div>
</div>
{% endblock body %}

curso/aperitivos/templates/aperitivos/video.html
{% extends 'base/base.html' %}
{% load static %}
{% block title %}Rios de Luz - Aperitivos{% endblock title %}
{% block description %}página do curso Rios de Luz{% endblock description %}
{% block body %}
<div class="container">
    <div class="row">
        <div class="col-md-12">
            <h1 class="mt-4 mb-3">{{ video.titulo | default:"Faltando titulo"}}</h1>
            <iframe src="https://player.vimeo.com/video/{{ video.vimeo_id }}" width="640" height="352" frameborder="0" allow="autoplay; fullscreen" allowfullscreen></iframe>
        </div>
    </div>
</div>
{% endblock body %}

curso/base/templates/base/base.html
{% load static %}
<!DOCTYPE html>
<html lang="pt-br">
  <head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">

    <title>{% block title %}Rios de Luz{% endblock title %}</title>

    <meta name="description" content="{% block description %}página do curso Rios de Luz{% endblock description %}">
    <meta name="author" content="Sergio Casas">
		<link rel="icon" type="image/png" href="{% static 'img/favicon.png' %}">
    <link href="{% static 'css/bootstrap.min.css' %}" rel="stylesheet">
	<link href="{% static 'css/style.css' %}" rel="stylesheet">
    <script src="{% static 'js/jquery.min.js' %}"></script>
    <script src="{% static 'js/bootstrap.min.js' %}"></script>
    <script src="{% static 'js/scripts.js' %}"></script>

  </head>
  <body>
	<nav class="navbar navbar-expand-lg navbar-light" style="background-color: #68c790;">
		<a class="navbar-brand" href="{% url 'base:home' %}">Rios de Luz</a>
		<button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
		  <span class="navbar-toggler-icon"></span>
		  
		</button>
	  
		<div class="collapse navbar-collapse" id="navbarSupportedContent">
		  <ul class="navbar-nav mr-auto">
			<li class="nav-item dropdown">
				<a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
				  Modulos
				</a>
				<div class="dropdown-menu" aria-labelledby="navbarDropdown">
					{% for modulo in MODULOS %}
					<a class="dropdown-item" href="{{modulo.get_absolute_url}}">{{modulo.titulo}}</a>
					<div class="dropdown-divider"></div>
					{% endfor %}
				</div>
			  </li>
			  
		  </ul>
		  {% if user.is_authenticated %}
		  <ul class="navbar-nav">
			<li class="nav-item dropdown">
				<a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
				  {{ user.first_name }}
				</a>
				<div class="dropdown-menu" aria-labelledby="navbarDropdown">
					<div class="dropdown-item">
					<a class="btn btn-danger" href="{% url 'logout' %}">Sair</a>
					</div>
				</div>
			  </li>
			  
		  </ul>
		  {% else %}
		  <a  class="btn btn-light my-2" href="{% url 'login' %}">Entrar</a>
		  {% endif %}
		</div>
	</nav>
	{% block body %}{% endblock body %}
    
{% include 'base/footer.html' with contato_email='contato@riosdeluz.brisaverde.life' only%}



  </body>
</html>

curso/base/templates/base/footer.html
<footer class='main-footer mt-5 pt-4 text-light' style='background-color:darkgreen'>
	<div class="container">
		<div class="row">
			<div class="col">
				<h3>Entre em contato</h3>
				<address>
					<a href="tel:+5512983010387">+55 12 98301-0387</a>
					<br/>
					<a href="mailto:{{ contato_email }}">{{ contato_email }}</a>
				</address>

			</div>
		</div>
	</div>
	<div class="rights pb-4" style="background-color: darkolivegreen;">
		<div class="container">
			<div class="row">
				<div class="col">
					{% now 'Y' %} Rios de Luz. Todos direitos reservados.
				</div>
			</div>
		</div>
	</div>
</footer>

curso/base/templates/base/home.html
{% load static %}
<!DOCTYPE html>
<html lang="pt-br">
  <head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">

    <title>Python Pro</title>

    <meta name="description" content="Página do curso Python Pro">
    <meta name="author" content="Renzo Nuccitelli">
	<link rel="icon" type="image/png" href="{% static 'img/favicon.png' %}" />
	<link href="{% static  'css/bootstrap.min.css'  %}" rel="stylesheet">
	<link href="{% static 'css/style.css '  %}" rel="stylesheet">
	<script src ="{% static 'js/jquery.min.js '  %}"></script>
	<script src ="{% static 'js/bootstrap.min.js '  %}"></script>
	<script src ="{% static 'js/scripts.js '  %}"></script>


  </head>
  <body>

	<nav class="navbar navbar-expand-lg navbar-dark bg-dark">
 		<div class="container-fluid">
 		   <a class="navbar-brand" href="{% url 'base:home' %}">Python Pro</a>
 		   <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
 		     <span class="navbar-toggler-icon"></span>
 		   </button>
 		    <div class="collapse navbar-collapse" id="navbarSupportedContent">
 		     <ul class="navbar-nav me-auto mb-2 mb-lg-0">
 		     </ul>
		  
 		    </div>
 		</div>


    	<div class="container-fluid">
		<div class="row">
			<div class="col-md-12">

				
				<div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
					<ul class="navbar-nav">
						<li class="nav-item active">
							 <a class="nav-link" href="#">Link <span class="sr-only">(current)</span></a>
						</li>
						<li class="nav-item">
							 <a class="nav-link" href="#">Link</a>
						</li>
						<li class="nav-item dropdown">
							 <a class="nav-link dropdown-toggle" href="http://example.com" id="navbarDropdownMenuLink" data-toggle="dropdown">Dropdown link</a>
							<div class="dropdown-menu" aria-labelledby="navbarDropdownMenuLink">
								 <a class="dropdown-item" href="#">Action</a> <a class="dropdown-item" href="#">Another action</a> <a class="dropdown-item" href="#">Something else here</a>
								<div class="dropdown-divider">
								</div> <a class="dropdown-item" href="#">Separated link</a>
							</div>
						</li>
					</ul>
					
				</div>
	</nav>

			<div class="jumbotron">
				<h2>
					Curso de Python com Luciano Ramalho
				</h2>
				<p>
					Confira em breve mais informações sobre o curso que será ministrado pelo autor do livro
					<a href="http://shop.oreilly.com/product/0636920032519.do" target="_blank" >Python Fluente</a>"
				</p>
			</div>
			<div class="row">
				<div class="col-md-12">
					<div class="card">
						<h5 class="card-header">
							Mais detalhes sobre o instrutor.
						</h5>
						<div class="card-body">
							<p class="card-text">
								<img src="{% static 'img/luciano-ramalho.png' %}" alt="Foto de Luciano Ramalho"
									 class="img-thumbnail float-left mr-3"/>
								Ramalho é sócio e professor na <a href="www.python.pro.br">Python Pro</a> e autor do
								Livro Python Fluente. Foi diretor técnico do Brasil Online, primeiro portal da Abril
								S/A na Web. Liderou times para os portais IDG Now, BOL, UOL, AOL Brasil e outros,
								usando Python desde 1998. Como instrutor, atendeu clientes como Citibank, CPqD, Serpro,
								Presidência da República, Globo.com e Itaú. Palestrante em eventos internacionais
								como FISL, PyCon US e OSCON. Ajudou a criar a Associação Python Brasil e foi seu
								presidente. É membro da Python Software Foundation e fundador do Garoa Hacker Clube,
								o primeiro hackerspace do Brasil.
							</p>
						</div>
					</div>
				</div>
			</div>
		</div>
	</div>
</div>


  </body>
</html>

curso/modulos/templates/modulos/aula_detalhe.html
{% extends 'base/base.html' %}
{% load static %}
{% block title %}Rios de Luz - Aperitivos{% endblock title %}
{% block description %}página do curso Rios de Luz{% endblock description %}
{% block body %}

  
  <nav aria-label="breadcrumb">
    <ol class="breadcrumb">
      <li class="breadcrumb-item"><a href="#">Home</a></li>
      <li class="breadcrumb-item"><a href="{{aula.modulo.get_absolute_url}}">{{aula.modulo.titulo}}</a></li>
      <li class="breadcrumb-item active" aria-current="page">{{aula.titulo}}</li>
    </ol>
  </nav>
<div class="container">
    <div class="row">
        <div class="col-md-12">
            <h1 class="mt-4 mb-3">{{ aula.titulo | default:"Faltando titulo"}}</h1>
            <iframe src="https://player.vimeo.com/video/{{ aula.vimeo_id }}" width="640" height="352" frameborder="0" allow="aulaplay; fullscreen" allowfullscreen></iframe>
        </div>
    </div>
</div>
{% endblock body %}

curso/modulos/templates/modulos/indice.html
{% extends 'base/base.html' %}
{% load static %}
{% block title %}{{modulo.titulo}}{% endblock title %}
{% block description %}página com detalhes do módulo {{ modulo.titulo}}{% endblock description %}
{% block body %}
<div class="container">
    {% for modulo in modulos %}
    <div class="row">
        <div class="col-md-12">
            <h1 class="mt-4 mb-3">{{ modulo.titulo }}</h1>
            <dl>
                <dt>Público </dt>
                <dd>{{ modulo.publico }}</dd>
                <dt>Descrição </dt>
                <dd>{{ modulo.descricao }}</dd>
            </dl>
            <h2>Aulas</h2>
            <ol>
                {% for aula in modulo.aulas %}
                <li><a href="{{ aula.get_absolute_url }}">{{ aula.titulo }}</a></li>
                {% endfor %}
            </ol>
        </div>
    </div>
    {% endfor %}
</div>
{% endblock body %}

curso/modulos/templates/modulos/modulo_detalhe.html
{% extends 'base/base.html' %}
{% load static %}
{% block title %}{{modulo.titulo}}{% endblock title %}
{% block description %}página com detalhes do módulo {{ modulo.titulo}}{% endblock description %}
{% block body %}
<div class="container">
    <div class="row">
        <div class="col-md-12">
            <h1 class="mt-4 mb-3">{{ modulo.titulo }}</h1>
            <dl>
                <dt>Público </dt>
                <dd>{{ modulo.publico }}</dd>
                <dt>Descrição </dt>
                <dd>{{ modulo.descricao }}</dd>
            </dl>
            <h2>Aulas</h2>
            <ol>
                {% for aula in aulas %}
                <li><a href="{{ aula.get_absolute_url }}">{{ aula.titulo }}</a></li>
                {% endfor %}
            </ol>
        </div>
    </div>
</div>
{% endblock body %}

curso/modulos/templates/modulos/modulo_form.html
<!DOCTYPE html>
<html lang="en">
    <head>
        <meta charset="utf-8">
        <title>Title</title>
        <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.5.1/jquery.min.js"></script>
        <script type="application/javascript">
            $(document).ready(function(){
                let $modulosSelect=$('#modulos-select')
                let $aulasSelect=$('#aulas-select')
                function buscarAulas(moduloSlug) {
                    $aulasSelect.empty();
                    $.get('/modulos/api/aulas/'+moduloSlug, function(data){
                        for (const aula in data.aulas){
                            let s = '<option value="'+ aula.slug+'">'+aula.titulo+' </option>'
                            $aulasSelect.append(s)
                        }
                    });
                }

                buscarAulas($modulosSelect.val());
                $modulosSelect.change(function(event){
                    buscarAulas($modulosSelect.val());
                });
            });
        </script>
    </head>
<body>
    <select id="modulos-select">
        {% for modulo in modulos %}
            <option value="{{ modulo.slug }}">{{ modulo.titulo}} </option>
        {% endfor %}
    </select>
    <select id="aulas-select"></select>
</body>
</html>

curso/turmas/templates/turmas/indice.html
{% extends 'base/base.html' %}
{% load static %}
{% block title %}Índice de Turmas{% endblock title %}
{% block description %}Página com todas as turmas do curso Rios de Luz {{ modulo.titulo}}{% endblock description %}
{% block body %}
<div class="container">
    {% for modulo in modulos %}
    <div class="row">
        <div class="col-md-12">
            <h1 class="mt-4 mb-3">{{ modulo.titulo }}</h1>
            <dl>
                <dt>Público </dt>
                <dd>{{ modulo.publico }}</dd>
                <dt>Descrição </dt>
                <dd>{{ modulo.descricao }}</dd>
            </dl>
            <h2>Aulas</h2>
            <ol>
                {% for aula in modulo.aulas %}
                <li><a href="{{ aula.get_absolute_url }}">{{ aula.titulo }}</a></li>
                {% endfor %}
            </ol>
        </div>
    </div>
    {% endfor %}
</div>
{% endblock body %}